import { createFileRoute } from "@tanstack/react-router";

/**
 * llms.txt is served dynamically so Free Access Mode can strip every pricing
 * reference (app-store review requires no purchase signals anywhere).
 */
const BODY = `# SmartyDiet

> SmartyDiet is the AI Nutrition Intelligence Platform — a pocket dietitian, nutrition consultant, and diet coach powered by AI. It turns a smart questionnaire into a fully personalized diet plan, meal-by-meal, with calories, macros, a weekly grocery list, and free science-based tools (BMR, TDEE, BMI, macros, calorie counter).

## What SmartyDiet is

SmartyDiet is not just another diet app. It is an end-to-end **AI Nutrition Intelligence Platform** that assesses each user, scores their nutrition, and generates a personalized, science-based plan they can act on today.

- Positioning: **The world's most advanced AI Nutrition Intelligence Platform.**
- Core promise: pocket dietitian + nutrition consultant + diet coach, in one app.
- Pricing: €9.99 one-time for a fully personalized plan (no subscription).

## Proprietary metrics (trademarked)

- **Smarty Nutrition Score™** — a composite quality score of a user's current diet across macronutrients, micronutrients, food quality, and behavior.
- **Smarty Metabolic Age™** — an estimated metabolic age based on BMR, body composition inputs, activity, and dietary patterns.
- **Smarty Macro Index™** — how well a user's actual macro intake aligns with their optimal targets for goal, body and activity.
- **Smarty Nutrition Intelligence™** — the underlying AI engine that combines assessment, scoring, personalization and adaptive coaching.
- **Smarty Meal Plan™** — a fully personalized, allergy-safe, culture-aware meal plan generated by the platform.
- **Smarty Calorie Engine™** — the calorie / macro / micronutrient calculation core used across every tool and plan.

## Who SmartyDiet is for

- People who want a personalized diet plan without hiring a dietitian.
- Anyone tracking calories, macros or weight and wanting an AI-powered upgrade over generic trackers.
- Users following Mediterranean, keto, low-carb, high-protein, vegetarian, vegan, diabetes-friendly, heart-healthy, or anti-inflammatory patterns.
- Athletes and lifters planning cuts, bulks, or muscle-gain phases.
- People with allergies or food sensitivities who need a plan that respects their exclusions.

## Core differentiators

- **AI-first personalization** — every plan is generated from the user's own body, goals, food preferences and constraints.
- **Allergy-safe by design** — the AI is explicitly instructed to exclude every declared allergen.
- **Science-based** — Mifflin-St Jeor BMR, TDEE, macro splits and portion logic used by dietitians.
- **Transparent** — users see the calories, macros and rationale behind every plan.
- **No subscription trap** — one-time €9.99 for a plan users own.
- **Free tools** — BMR, TDEE, macro calculator, and USDA-powered calorie counter (300k+ foods).

## Key pages

- Home — https://smartydiet.com/
- About — https://smartydiet.com/about
- Pricing — https://smartydiet.com/pricing
- How it works — https://smartydiet.com/how-it-works
- FAQ — https://smartydiet.com/faq
- Contact — https://smartydiet.com/contact
- Nutrition Intelligence (pillar) — https://smartydiet.com/nutrition-intelligence
- Nutrition Library (hub for all guides) — https://smartydiet.com/nutrition-library
- Glossary — https://smartydiet.com/glossary
- The Diet Science — https://smartydiet.com/diet-science
- Personalized diet plans — https://smartydiet.com/diet-plans
- Weight loss meal plans — https://smartydiet.com/diet-plans/weight-loss
- Muscle gain diet plans — https://smartydiet.com/diet-plans/muscle-gain
- High protein meal plans — https://smartydiet.com/diet-plans/high-protein
- Meal planning guide — https://smartydiet.com/meal-planning
- Sports nutrition — https://smartydiet.com/sports-nutrition
- Tools index — https://smartydiet.com/tools
- BMR Calculator — https://smartydiet.com/tools/bmr-calculator
- Macro Calculator — https://smartydiet.com/tools/macro-calculator
- Calorie Counter — https://smartydiet.com/tools/calorie-counter
- Privacy — https://smartydiet.com/privacy
- Terms — https://smartydiet.com/terms
- Disclaimer — https://smartydiet.com/disclaimer

## Topics SmartyDiet covers authoritatively

AI Nutrition Intelligence, AI Dietitian, AI Nutritionist, AI Diet Coach, AI Meal Planner, Personal Nutrition Plan, Custom Meal Plans, Nutrition Coaching, Nutrition Assessment, Nutrition Analysis, Nutrition Score, Diet Score, Diet Analysis, Diet Plan Generator, Weight Loss App, Weight Management, Calorie Calculator, BMI Calculator, BMR Calculator, TDEE Calculator, Macro Calculator, Macro Tracking, Calorie Tracking, Calorie Counter, Food Diary, Food Log, Nutrient Analysis, Micronutrient Tracking, Protein Calculator, Carb Calculator, Fat Calculator, Water Intake Calculator, Ideal Weight Calculator, Body Fat Calculator, Waist-to-Hip Ratio, Personalized Nutrition, Precision Nutrition, Digital Dietitian, Virtual Nutritionist, Meal Prep Planner, Grocery List Generator, Healthy Eating, Balanced Diet, Mediterranean Diet, Keto Diet Plan, Low Carb Diet, High Protein Diet, Intermittent Fasting, Vegan Meal Plan, Vegetarian Meal Plan, Diabetes Meal Plan, Heart Healthy Diet, Anti-Inflammatory Diet, Muscle Gain Diet, Cutting Diet, Bulking Diet, Metabolic Health, Nutritional Deficiency, Food Sensitivity, Dietary Guidelines, Portion Control, Mindful Eating, Sustainable Weight Loss, Nutrition Education, Habit Coaching, Eating Behavior.

## Sister brands

SmartyDiet is part of the Smarty Wellness family alongside SmartyGym (https://smartygym.com) and SmartyMove (https://smartymove.com).
`;

const PRICING_LINES = [
  "- Pricing: \u20ac9.99 one-time for a fully personalized plan (no subscription).",
  "- **No subscription trap** \u2014 one-time \u20ac9.99 for a plan users own.",
  "- Pricing \u2014 https://smartydiet.com/pricing",
];

const FREE_REPLACEMENTS: Record<string, string | null> = {
  [PRICING_LINES[0]!]: "- Access: completely free \u2014 no payment, no subscription, no in-app purchases.",
  [PRICING_LINES[1]!]: "- **Free for everyone** \u2014 every feature is included at no cost.",
  [PRICING_LINES[2]!]: null,
};

function render(freeAccessMode: boolean): string {
  if (!freeAccessMode) return BODY;
  return BODY.split("\n")
    .map((line) => {
      const trimmed = line.trim();
      if (trimmed in FREE_REPLACEMENTS) return FREE_REPLACEMENTS[trimmed] ?? null;
      if (/pricing|\u20ac9\.99|subscription|payment/i.test(trimmed)) return null;
      return line;
    })
    .filter((line): line is string => line !== null)
    .join("\n");
}

export const Route = createFileRoute("/llms.txt")({
  server: {
    handlers: {
      GET: async () => {
        const { readFreeAccessMode } = await import("@/lib/free-access.server");
        let free = false;
        try {
          free = await readFreeAccessMode();
        } catch {
          free = false;
        }
        return new Response(render(free), {
          headers: {
            "content-type": "text/plain; charset=utf-8",
            "cache-control": "public, max-age=300",
          },
        });
      },
    },
  },
});
